### ISSUE TITLE
GetDemoDirectDownloadUrl returning empty string for demo

### ISSUE THREAD

**Issue by lay295** [ArttuKuikka/HltvSharp#8]
Hey, first off thanks for the awesome library :) helpful for a small project I wanted to do.

It seems [GetDemoDirectDownloadUrl](https://github.com/ArttuKuikka/HltvSharp/blob/084b74c40e19796e8f87d02ffc55fbf5ba2b5f53/HltvSharp/Parsing/GetMatch.cs#L319) is returning an empty string for me, and it looks like the WebException is never being thrown and caught for me. I'm using .NET 6 if that matters. Could you set the location from the response header if the exception is never thrown? I could make a PR if you'd prefer.

![image](https://user-images.githubusercontent.com/1060681/177247361-75ed0ddb-8eed-4192-9f10-ddc7c61becd8.png)

**Comment by ArttuKuikka** [comment]
First if all i kinda abandoned this project because of how big it would have to be but i can look into it

**Comment by ArttuKuikka** [comment]
Also if you can fix it just create a pull request and i will merge it because im not at home right now

**Comment by ArttuKuikka** [comment]
This issue is now fixed in the latest commit and in the nuget version 1.11
