### ISSUE TITLE
Could I use HltvSharp code in my repo?

### ISSUE THREAD

**Issue by ZjzMisaka** [ArttuKuikka/HltvSharp#9]
My code work on net framework, so I can not use your nuget package. 
I found your project have no licence, could I copy your code into my repo?
thank you.

**Comment by ArttuKuikka** [comment]
Hi. Yes you can freely use hltvsharp in your code and the reason it doesn't have a license is because haven't really explored all the available options since i'm quite new to open source and coding, also hltvsharp isn't really maintained so it might not fully work so be prepared for that
